export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATES_FORM = 'VALIDATES_FORM';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const PROJECT_TASKS = 'PROJECT_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const VALIDATES_TASK = 'VALIDATES_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const STATE_TASK = 'STATE_TASK';
export const CURRENT_TASK = 'CURRENT_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
